//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/ArgumentCaptor.java
//

#ifndef _OrgMockitoArgumentCaptor_H_
#define _OrgMockitoArgumentCaptor_H_

@class IOSClass;
@class OrgMockitoInternalMatchersCapturingMatcher;
@class OrgMockitoInternalProgressHandyReturnValues;
@protocol JavaUtilList;

#import "JreEmulation.h"

@interface OrgMockitoArgumentCaptor : NSObject {
 @public
  OrgMockitoInternalProgressHandyReturnValues *handyReturnValues_;
  OrgMockitoInternalMatchersCapturingMatcher *capturingMatcher_;
  IOSClass *clazz_;
}

- (instancetype)init;

- (instancetype)initWithIOSClass:(IOSClass *)clazz;

- (id)capture;

- (id)getValue;

- (id<JavaUtilList>)getAllValues;

+ (OrgMockitoArgumentCaptor *)forClassWithIOSClass:(IOSClass *)clazz;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoArgumentCaptor *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoArgumentCaptor_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoArgumentCaptor, handyReturnValues_, OrgMockitoInternalProgressHandyReturnValues *)
J2OBJC_FIELD_SETTER(OrgMockitoArgumentCaptor, capturingMatcher_, OrgMockitoInternalMatchersCapturingMatcher *)
J2OBJC_FIELD_SETTER(OrgMockitoArgumentCaptor, clazz_, IOSClass *)

#endif // _OrgMockitoArgumentCaptor_H_
