//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/Captor.java
//

#ifndef _OrgMockitoCaptor_H_
#define _OrgMockitoCaptor_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgMockitoCaptor < JavaLangAnnotationAnnotation >

@end

@interface OrgMockitoCaptor : NSObject < OrgMockitoCaptor >

@end

__attribute__((always_inline)) inline void OrgMockitoCaptor_init() {}

#endif // _OrgMockitoCaptor_H_
