//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/Incubating.java
//

#ifndef _OrgMockitoIncubating_H_
#define _OrgMockitoIncubating_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgMockitoIncubating < JavaLangAnnotationAnnotation >

@end

@interface OrgMockitoIncubating : NSObject < OrgMockitoIncubating >

@end

__attribute__((always_inline)) inline void OrgMockitoIncubating_init() {}

#endif // _OrgMockitoIncubating_H_
