//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/InjectMocks.java
//

#ifndef _OrgMockitoInjectMocks_H_
#define _OrgMockitoInjectMocks_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgMockitoInjectMocks < JavaLangAnnotationAnnotation >

@end

@interface OrgMockitoInjectMocks : NSObject < OrgMockitoInjectMocks >

@end

__attribute__((always_inline)) inline void OrgMockitoInjectMocks_init() {}

#endif // _OrgMockitoInjectMocks_H_
