//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/InOrder.java
//

#ifndef _OrgMockitoInOrder_H_
#define _OrgMockitoInOrder_H_

@protocol OrgMockitoVerificationVerificationMode;

#import "JreEmulation.h"

@protocol OrgMockitoInOrder < NSObject, JavaObject >

- (id)verifyWithId:(id)mock;

- (id)verifyWithId:(id)mock
withOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)mode;

- (void)verifyNoMoreInteractions;

@end

__attribute__((always_inline)) inline void OrgMockitoInOrder_init() {}

#endif // _OrgMockitoInOrder_H_
