//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/MockitoAnnotations.java
//

#ifndef _OrgMockitoMockitoAnnotations_H_
#define _OrgMockitoMockitoAnnotations_H_

@class IOSClass;
@class JavaLangReflectField;
@protocol OrgMockitoConfigurationAnnotationEngine;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@interface OrgMockitoMockitoAnnotations : NSObject {
}

+ (void)initMocksWithId:(id)testClass OBJC_METHOD_FAMILY_NONE;

+ (void)scanDeprecatedWayWithOrgMockitoConfigurationAnnotationEngine:(id<OrgMockitoConfigurationAnnotationEngine>)annotationEngine
                                                              withId:(id)testClass
                                                        withIOSClass:(IOSClass *)clazz;

+ (void)processAnnotationDeprecatedWayWithOrgMockitoConfigurationAnnotationEngine:(id<OrgMockitoConfigurationAnnotationEngine>)annotationEngine
                                                                           withId:(id)testClass
                                                         withJavaLangReflectField:(JavaLangReflectField *)field;

+ (void)throwIfAlreadyAssignedWithJavaLangReflectField:(JavaLangReflectField *)field
                                           withBoolean:(jboolean)alreadyAssigned;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoMockitoAnnotations_init() {}

@protocol OrgMockitoMockitoAnnotations_Mock < JavaLangAnnotationAnnotation >

@end

@interface OrgMockitoMockitoAnnotations_Mock : NSObject < OrgMockitoMockitoAnnotations_Mock >

@end

__attribute__((always_inline)) inline void OrgMockitoMockitoAnnotations_Mock_init() {}

#endif // _OrgMockitoMockitoAnnotations_H_
