//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/MockingDetails.java
//

#ifndef _OrgMockitoMockingDetails_H_
#define _OrgMockitoMockingDetails_H_

#import "JreEmulation.h"

@protocol OrgMockitoMockingDetails < NSObject, JavaObject >

- (jboolean)isMock;

- (jboolean)isSpy;

@end

__attribute__((always_inline)) inline void OrgMockitoMockingDetails_init() {}

#endif // _OrgMockitoMockingDetails_H_
