//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/Mockito.java
//

#ifndef _OrgMockitoMockito_H_
#define _OrgMockitoMockito_H_

@class IOSClass;
@class IOSObjectArray;
@class JavaLangThrowable;
@class OrgMockitoInternalMockitoCore;
@protocol OrgMockitoInOrder;
@protocol OrgMockitoMockSettings;
@protocol OrgMockitoMockingDetails;
@protocol OrgMockitoMockitoDebugger;
@protocol OrgMockitoReturnValues;
@protocol OrgMockitoStubbingAnswer;
@protocol OrgMockitoStubbingDeprecatedOngoingStubbing;
@protocol OrgMockitoStubbingOngoingStubbing;
@protocol OrgMockitoStubbingStubber;
@protocol OrgMockitoStubbingVoidMethodStubbable;
@protocol OrgMockitoVerificationVerificationMode;
@protocol OrgMockitoVerificationVerificationWithTimeout;

#import "JreEmulation.h"
#include "org/mockito/Matchers.h"

@interface OrgMockitoMockito : OrgMockitoMatchers {
}

+ (id)mockWithIOSClass:(IOSClass *)classToMock;

+ (id)mockWithIOSClass:(IOSClass *)classToMock
          withNSString:(NSString *)name;

+ (id<OrgMockitoMockingDetails>)mockingDetailsWithId:(id)toInspect;

+ (id)mockWithIOSClass:(IOSClass *)classToMock
withOrgMockitoReturnValues:(id<OrgMockitoReturnValues>)returnValues;

+ (id)mockWithIOSClass:(IOSClass *)classToMock
withOrgMockitoStubbingAnswer:(id<OrgMockitoStubbingAnswer>)defaultAnswer;

+ (id)mockWithIOSClass:(IOSClass *)classToMock
withOrgMockitoMockSettings:(id<OrgMockitoMockSettings>)mockSettings;

+ (id)spyWithId:(id)object;

+ (id<OrgMockitoStubbingDeprecatedOngoingStubbing>)stubWithId:(id)methodCall;

+ (id<OrgMockitoStubbingOngoingStubbing>)whenWithId:(id)methodCall;

+ (id)verifyWithId:(id)mock;

+ (id)verifyWithId:(id)mock
withOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)mode;

+ (void)resetWithNSObjectArray:(IOSObjectArray *)mocks;

+ (void)verifyNoMoreInteractionsWithNSObjectArray:(IOSObjectArray *)mocks;

+ (void)verifyZeroInteractionsWithNSObjectArray:(IOSObjectArray *)mocks;

+ (id<OrgMockitoStubbingVoidMethodStubbable>)stubVoidWithId:(id)mock;

+ (id<OrgMockitoStubbingStubber>)doThrowWithJavaLangThrowable:(JavaLangThrowable *)toBeThrown;

+ (id<OrgMockitoStubbingStubber>)doThrowWithIOSClass:(IOSClass *)toBeThrown;

+ (id<OrgMockitoStubbingStubber>)doCallRealMethod;

+ (id<OrgMockitoStubbingStubber>)doAnswerWithOrgMockitoStubbingAnswer:(id<OrgMockitoStubbingAnswer>)answer;

+ (id<OrgMockitoStubbingStubber>)doNothing;

+ (id<OrgMockitoStubbingStubber>)doReturnWithId:(id)toBeReturned;

+ (id<OrgMockitoInOrder>)inOrderWithNSObjectArray:(IOSObjectArray *)mocks;

+ (IOSObjectArray *)ignoreStubsWithNSObjectArray:(IOSObjectArray *)mocks;

+ (id<OrgMockitoVerificationVerificationMode>)timesWithInt:(jint)wantedNumberOfInvocations;

+ (id<OrgMockitoVerificationVerificationMode>)never;

+ (id<OrgMockitoVerificationVerificationMode>)atLeastOnce;

+ (id<OrgMockitoVerificationVerificationMode>)atLeastWithInt:(jint)minNumberOfInvocations;

+ (id<OrgMockitoVerificationVerificationMode>)atMostWithInt:(jint)maxNumberOfInvocations;

+ (id<OrgMockitoVerificationVerificationMode>)callsWithInt:(jint)wantedNumberOfInvocations;

+ (id<OrgMockitoVerificationVerificationMode>)only;

+ (id<OrgMockitoVerificationVerificationWithTimeout>)timeoutWithInt:(jint)millis;

+ (void)validateMockitoUsage;

+ (id<OrgMockitoMockSettings>)withSettings;

+ (id<OrgMockitoMockitoDebugger>)debug;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgMockitoMockito_initialized;
J2OBJC_STATIC_INIT(OrgMockitoMockito)

FOUNDATION_EXPORT OrgMockitoInternalMockitoCore *OrgMockitoMockito_MOCKITO_CORE_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoMockito, MOCKITO_CORE_, OrgMockitoInternalMockitoCore *)

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoMockito_RETURNS_DEFAULTS_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoMockito, RETURNS_DEFAULTS_, id<OrgMockitoStubbingAnswer>)

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoMockito_RETURNS_SMART_NULLS_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoMockito, RETURNS_SMART_NULLS_, id<OrgMockitoStubbingAnswer>)

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoMockito_RETURNS_MOCKS_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoMockito, RETURNS_MOCKS_, id<OrgMockitoStubbingAnswer>)

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoMockito_RETURNS_DEEP_STUBS_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoMockito, RETURNS_DEEP_STUBS_, id<OrgMockitoStubbingAnswer>)

FOUNDATION_EXPORT id<OrgMockitoStubbingAnswer> OrgMockitoMockito_CALLS_REAL_METHODS_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoMockito, CALLS_REAL_METHODS_, id<OrgMockitoStubbingAnswer>)

#endif // _OrgMockitoMockito_H_
