//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/Spy.java
//

#ifndef _OrgMockitoSpy_H_
#define _OrgMockitoSpy_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgMockitoSpy < JavaLangAnnotationAnnotation >

@end

@interface OrgMockitoSpy : NSObject < OrgMockitoSpy >

@end

__attribute__((always_inline)) inline void OrgMockitoSpy_init() {}

#endif // _OrgMockitoSpy_H_
