//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/util/reflection/Whitebox.java
//

#ifndef _OrgMockitoInternalUtilReflectionWhitebox_H_
#define _OrgMockitoInternalUtilReflectionWhitebox_H_

@class IOSClass;
@class JavaLangReflectField;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilReflectionWhitebox : NSObject {
}

+ (id)getInternalStateWithId:(id)target
                withNSString:(NSString *)field;

+ (void)setInternalStateWithId:(id)target
                  withNSString:(NSString *)field
                        withId:(id)value;

+ (JavaLangReflectField *)getFieldFromHierarchyWithIOSClass:(IOSClass *)clazz
                                               withNSString:(NSString *)field;

+ (JavaLangReflectField *)getFieldWithIOSClass:(IOSClass *)clazz
                                  withNSString:(NSString *)field;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilReflectionWhitebox_init() {}

#endif // _OrgMockitoInternalUtilReflectionWhitebox_H_
