//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/hamcrest/Factory.java
//

#ifndef _OrgHamcrestFactory_H_
#define _OrgHamcrestFactory_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgHamcrestFactory < JavaLangAnnotationAnnotation >

@end

@interface OrgHamcrestFactory : NSObject < OrgHamcrestFactory >

@end

__attribute__((always_inline)) inline void OrgHamcrestFactory_init() {}

#endif // _OrgHamcrestFactory_H_
