//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/junit/runner/Version.java
//

#ifndef _JunitRunnerVersion_H_
#define _JunitRunnerVersion_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@interface JunitRunnerVersion : NSObject {
}

- (instancetype)init;

+ (NSString *)id__;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

__attribute__((always_inline)) inline void JunitRunnerVersion_init() {}

#endif // _JunitRunnerVersion_H_
