//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/regex/Matcher.java
//

#ifndef _JavaUtilRegexMatcher_H_
#define _JavaUtilRegexMatcher_H_

@class IOSIntArray;
@class JavaLangStringBuffer;
@class JavaUtilRegexPattern;
@protocol JavaLangCharSequence;

#import "JreEmulation.h"
#include "java/util/regex/MatchResult.h"

@interface JavaUtilRegexMatcher : NSObject < JavaUtilRegexMatchResult > {
}

- (instancetype)initWithJavaUtilRegexPattern:(JavaUtilRegexPattern *)pattern
                    withJavaLangCharSequence:(id<JavaLangCharSequence>)input;

- (JavaUtilRegexMatcher *)appendReplacementWithJavaLangStringBuffer:(JavaLangStringBuffer *)buffer
                                                       withNSString:(NSString *)replacement;

- (JavaUtilRegexMatcher *)reset;

- (JavaUtilRegexMatcher *)resetWithJavaLangCharSequence:(id<JavaLangCharSequence>)input;

- (JavaUtilRegexMatcher *)usePatternWithJavaUtilRegexPattern:(JavaUtilRegexPattern *)pattern;

- (JavaUtilRegexMatcher *)regionWithInt:(jint)start
                                withInt:(jint)end;

- (JavaLangStringBuffer *)appendTailWithJavaLangStringBuffer:(JavaLangStringBuffer *)buffer;

- (NSString *)replaceFirstWithNSString:(NSString *)replacement;

- (NSString *)replaceAllWithNSString:(NSString *)replacement;

- (JavaUtilRegexPattern *)pattern;

- (NSString *)groupWithInt:(jint)group;

- (NSString *)group;

- (jboolean)findWithInt:(jint)start;

- (jboolean)find;

- (jboolean)lookingAt;

- (jboolean)matches;

- (jint)startWithInt:(jint)group;

- (jint)endWithInt:(jint)group;

+ (NSString *)quoteReplacementWithNSString:(NSString *)s;

- (jint)start;

- (jint)groupCount;

- (jint)end;

- (id<JavaUtilRegexMatchResult>)toMatchResult;

- (JavaUtilRegexMatcher *)useAnchoringBoundsWithBoolean:(jboolean)value;

- (jboolean)hasAnchoringBounds;

- (JavaUtilRegexMatcher *)useTransparentBoundsWithBoolean:(jboolean)value;

- (jboolean)hasTransparentBounds;

- (jint)regionStart;

- (jint)regionEnd;

- (jboolean)requireEnd;

- (jboolean)hitEnd;

@end

__attribute__((always_inline)) inline void JavaUtilRegexMatcher_init() {}
FOUNDATION_EXPORT NSString *JavaUtilRegexMatcher_quoteReplacementWithNSString_(NSString *s);

#endif // _JavaUtilRegexMatcher_H_
