//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/verification/VerificationModeFactory.java
//

#ifndef _OrgMockitoInternalVerificationVerificationModeFactory_H_
#define _OrgMockitoInternalVerificationVerificationModeFactory_H_

@class OrgMockitoInternalVerificationCalls;
@class OrgMockitoInternalVerificationNoMoreInteractions;
@class OrgMockitoInternalVerificationTimes;
@protocol OrgMockitoVerificationVerificationMode;

#import "JreEmulation.h"

@interface OrgMockitoInternalVerificationVerificationModeFactory : NSObject {
}

+ (id<OrgMockitoVerificationVerificationMode>)atLeastOnce;

+ (id<OrgMockitoVerificationVerificationMode>)atLeastWithInt:(jint)minNumberOfInvocations;

+ (id<OrgMockitoVerificationVerificationMode>)only;

+ (OrgMockitoInternalVerificationTimes *)timesWithInt:(jint)wantedNumberOfInvocations;

+ (OrgMockitoInternalVerificationCalls *)callsWithInt:(jint)wantedNumberOfInvocations;

+ (OrgMockitoInternalVerificationNoMoreInteractions *)noMoreInteractions;

+ (id<OrgMockitoVerificationVerificationMode>)atMostWithInt:(jint)maxNumberOfInvocations;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalVerificationVerificationModeFactory_init() {}

#endif // _OrgMockitoInternalVerificationVerificationModeFactory_H_
