//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/meta/Exclusive.java
//

#ifndef _JavaxAnnotationMetaExclusive_H_
#define _JavaxAnnotationMetaExclusive_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationMetaExclusive < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationMetaExclusive : NSObject < JavaxAnnotationMetaExclusive >

@end

__attribute__((always_inline)) inline void JavaxAnnotationMetaExclusive_init() {}

#endif // _JavaxAnnotationMetaExclusive_H_
