//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/meta/TypeQualifierNickname.java
//

#ifndef _JavaxAnnotationMetaTypeQualifierNickname_H_
#define _JavaxAnnotationMetaTypeQualifierNickname_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationMetaTypeQualifierNickname < JavaLangAnnotationAnnotation >

@end

#endif // _JavaxAnnotationMetaTypeQualifierNickname_H_
