//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.7/jsr305/build_result/java/javax/annotation/meta/TypeQualifierNickname.java
//

#ifndef _JavaxAnnotationMetaTypeQualifierNickname_H_
#define _JavaxAnnotationMetaTypeQualifierNickname_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationMetaTypeQualifierNickname < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxAnnotationMetaTypeQualifierNickname)

J2OBJC_TYPE_LITERAL_HEADER(JavaxAnnotationMetaTypeQualifierNickname)

#endif // _JavaxAnnotationMetaTypeQualifierNickname_H_
