//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/org/apache/harmony/luni/platform/Endianness.java
//

#ifndef _OrgApacheHarmonyLuniPlatformEndianness_H_
#define _OrgApacheHarmonyLuniPlatformEndianness_H_

#import "JreEmulation.h"

@interface OrgApacheHarmonyLuniPlatformEndianness : NSObject {
}

- (NSString *)description;

@end

FOUNDATION_EXPORT BOOL OrgApacheHarmonyLuniPlatformEndianness_initialized;
J2OBJC_STATIC_INIT(OrgApacheHarmonyLuniPlatformEndianness)

FOUNDATION_EXPORT OrgApacheHarmonyLuniPlatformEndianness *OrgApacheHarmonyLuniPlatformEndianness_BIG_ENDIAN__;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyLuniPlatformEndianness, BIG_ENDIAN__, OrgApacheHarmonyLuniPlatformEndianness *)

FOUNDATION_EXPORT OrgApacheHarmonyLuniPlatformEndianness *OrgApacheHarmonyLuniPlatformEndianness_LITTLE_ENDIAN__;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyLuniPlatformEndianness, LITTLE_ENDIAN__, OrgApacheHarmonyLuniPlatformEndianness *)

#endif // _OrgApacheHarmonyLuniPlatformEndianness_H_
