//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/junit/JUnitTool.java
//

#ifndef _OrgMockitoInternalJunitJUnitTool_H_
#define _OrgMockitoInternalJunitJUnitTool_H_

@class JavaLangAssertionError;

#import "JreEmulation.h"

@interface OrgMockitoInternalJunitJUnitTool : NSObject {
}

+ (jboolean)hasJUnit;

+ (JavaLangAssertionError *)createArgumentsAreDifferentExceptionWithNSString:(NSString *)message
                                                                withNSString:(NSString *)wanted
                                                                withNSString:(NSString *)actual;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgMockitoInternalJunitJUnitTool_initialized;
J2OBJC_STATIC_INIT(OrgMockitoInternalJunitJUnitTool)

FOUNDATION_EXPORT jboolean OrgMockitoInternalJunitJUnitTool_hasJUnit__;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalJunitJUnitTool, hasJUnit__, jboolean)
J2OBJC_STATIC_FIELD_REF_GETTER(OrgMockitoInternalJunitJUnitTool, hasJUnit__, jboolean)

#endif // _OrgMockitoInternalJunitJUnitTool_H_
