//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/mock/MockName.java
//

#ifndef _OrgMockitoMockMockName_H_
#define _OrgMockitoMockMockName_H_

#import "JreEmulation.h"

@protocol OrgMockitoMockMockName < NSObject, JavaObject >

- (NSString *)description;

- (jboolean)isDefault;

@end

__attribute__((always_inline)) inline void OrgMockitoMockMockName_init() {}

#endif // _OrgMockitoMockMockName_H_
