//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/configuration/injection/filter/MockCandidateFilter.java
//

#ifndef _OrgMockitoInternalConfigurationInjectionFilterMockCandidateFilter_H_
#define _OrgMockitoInternalConfigurationInjectionFilterMockCandidateFilter_H_

@class JavaLangReflectField;
@protocol JavaUtilCollection;
@protocol OrgMockitoInternalConfigurationInjectionFilterOngoingInjecter;

#import "JreEmulation.h"

@protocol OrgMockitoInternalConfigurationInjectionFilterMockCandidateFilter < NSObject, JavaObject >

- (id<OrgMockitoInternalConfigurationInjectionFilterOngoingInjecter>)filterCandidateWithJavaUtilCollection:(id<JavaUtilCollection>)mocks
                                                                                  withJavaLangReflectField:(JavaLangReflectField *)fieldToBeInjected
                                                                                                    withId:(id)fieldInstance;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalConfigurationInjectionFilterMockCandidateFilter_init() {}

#endif // _OrgMockitoInternalConfigurationInjectionFilterMockCandidateFilter_H_
