//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/configuration/injection/filter/OngoingInjecter.java
//

#ifndef _OrgMockitoInternalConfigurationInjectionFilterOngoingInjecter_H_
#define _OrgMockitoInternalConfigurationInjectionFilterOngoingInjecter_H_

#import "JreEmulation.h"

@protocol OrgMockitoInternalConfigurationInjectionFilterOngoingInjecter < NSObject, JavaObject >

- (id)thenInject;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalConfigurationInjectionFilterOngoingInjecter_init() {}

#endif // _OrgMockitoInternalConfigurationInjectionFilterOngoingInjecter_H_
