//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/listeners/MockingProgressListener.java
//

#ifndef _OrgMockitoInternalListenersMockingProgressListener_H_
#define _OrgMockitoInternalListenersMockingProgressListener_H_

#import "JreEmulation.h"

@protocol OrgMockitoInternalListenersMockingProgressListener < NSObject, JavaObject >

@end

__attribute__((always_inline)) inline void OrgMockitoInternalListenersMockingProgressListener_init() {}

#endif // _OrgMockitoInternalListenersMockingProgressListener_H_
