//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/guava/sources/com/google/common/base/Predicate.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonBasePredicate_RESTRICT
#define ComGoogleCommonBasePredicate_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonBasePredicate_RESTRICT

#if !defined (_ComGoogleCommonBasePredicate_) && (ComGoogleCommonBasePredicate_INCLUDE_ALL || ComGoogleCommonBasePredicate_INCLUDE)
#define _ComGoogleCommonBasePredicate_

@protocol ComGoogleCommonBasePredicate < NSObject, JavaObject >

- (jboolean)applyWithId:(id)input;

- (jboolean)isEqual:(id)object;

@end

__attribute__((always_inline)) inline void ComGoogleCommonBasePredicate_init() {}
#endif
