//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/util/Checks.java
//

#ifndef _OrgMockitoInternalUtilChecks_H_
#define _OrgMockitoInternalUtilChecks_H_

@protocol JavaLangIterable;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilChecks : NSObject {
}

+ (id)checkNotNullWithId:(id)value
            withNSString:(NSString *)checkedValue;

+ (id)checkItemsNotNullWithJavaLangIterable:(id<JavaLangIterable>)iterable
                               withNSString:(NSString *)checkedIterable;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilChecks_init() {}

#endif // _OrgMockitoInternalUtilChecks_H_
