//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/util/Decamelizer.java
//

#ifndef _OrgMockitoInternalUtilDecamelizer_H_
#define _OrgMockitoInternalUtilDecamelizer_H_

@class JavaUtilRegexPattern;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilDecamelizer : NSObject {
}

+ (NSString *)decamelizeMatcherWithNSString:(NSString *)className_;

+ (NSString *)decamelizeClassNameWithNSString:(NSString *)className_;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgMockitoInternalUtilDecamelizer_initialized;
J2OBJC_STATIC_INIT(OrgMockitoInternalUtilDecamelizer)

FOUNDATION_EXPORT JavaUtilRegexPattern *OrgMockitoInternalUtilDecamelizer_CAPS_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalUtilDecamelizer, CAPS_, JavaUtilRegexPattern *)

#endif // _OrgMockitoInternalUtilDecamelizer_H_
