//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/util/Primitives.java
//

#ifndef _OrgMockitoInternalUtilPrimitives_H_
#define _OrgMockitoInternalUtilPrimitives_H_

@class IOSClass;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilPrimitives : NSObject {
}

+ (IOSClass *)primitiveTypeOfWithIOSClass:(IOSClass *)clazz;

+ (jboolean)isPrimitiveOrWrapperWithIOSClass:(IOSClass *)type;

+ (id)defaultValueForPrimitiveOrWrapperWithIOSClass:(IOSClass *)primitiveOrWrapperType;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgMockitoInternalUtilPrimitives_initialized;
J2OBJC_STATIC_INIT(OrgMockitoInternalUtilPrimitives)

FOUNDATION_EXPORT id<JavaUtilMap> OrgMockitoInternalUtilPrimitives_primitiveTypes_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalUtilPrimitives, primitiveTypes_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgMockitoInternalUtilPrimitives, primitiveTypes_, id<JavaUtilMap>)

FOUNDATION_EXPORT id<JavaUtilMap> OrgMockitoInternalUtilPrimitives_primitiveOrWrapperDefaultValues_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalUtilPrimitives, primitiveOrWrapperDefaultValues_, id<JavaUtilMap>)
J2OBJC_STATIC_FIELD_SETTER(OrgMockitoInternalUtilPrimitives, primitiveOrWrapperDefaultValues_, id<JavaUtilMap>)

#endif // _OrgMockitoInternalUtilPrimitives_H_
