//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/util/StringJoiner.java
//

#ifndef _OrgMockitoInternalUtilStringJoiner_H_
#define _OrgMockitoInternalUtilStringJoiner_H_

@class IOSObjectArray;
@class JavaLangStringBuilder;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilStringJoiner : NSObject {
}

+ (NSString *)joinWithNSObjectArray:(IOSObjectArray *)linesToBreak;

+ (NSString *)joinWithJavaLangStringBuilder:(JavaLangStringBuilder *)outArg
                          withNSObjectArray:(IOSObjectArray *)linesToBreak;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilStringJoiner_init() {}

#endif // _OrgMockitoInternalUtilStringJoiner_H_
