//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/Readable.java
//

#ifndef _JavaLangReadable_H_
#define _JavaLangReadable_H_

@class JavaNioCharBuffer;

#import "JreEmulation.h"

@protocol JavaLangReadable < NSObject, JavaObject >

- (jint)readWithJavaNioCharBuffer:(JavaNioCharBuffer *)cb;

@end

__attribute__((always_inline)) inline void JavaLangReadable_init() {}

#endif // _JavaLangReadable_H_
