//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/java/lang/StackTraceElement.java
//

#ifndef _JavaLangStackTraceElement_H_
#define _JavaLangStackTraceElement_H_

#import "JreEmulation.h"

@interface JavaLangStackTraceElement : NSObject {
}

- (NSString *)getClassName;

- (NSString *)getMethodName;

- (NSString *)getFileName;

- (jint)getLineNumber;

- (instancetype)initWithNSString:(NSString *)className_
                    withNSString:(NSString *)methodName
                    withNSString:(NSString *)fileName
                         withInt:(jint)lineNumber;

- (instancetype)initWithLong:(jlong)address;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void JavaLangStackTraceElement_init() {}

#endif // _JavaLangStackTraceElement_H_
