//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/StrictMath.java
//

#ifndef _JavaLangStrictMath_H_
#define _JavaLangStrictMath_H_

@class JavaUtilRandom;

#import "JreEmulation.h"

#define JavaLangStrictMath_E 2.718281828459045
#define JavaLangStrictMath_PI 3.141592653589793

@interface JavaLangStrictMath : NSObject {
}

+ (jdouble)absWithDouble:(jdouble)d;

+ (jfloat)absWithFloat:(jfloat)f;

+ (jint)absWithInt:(jint)i;

+ (jlong)absWithLong:(jlong)l;

+ (jdouble)acosWithDouble:(jdouble)d;

+ (jdouble)asinWithDouble:(jdouble)d;

+ (jdouble)atanWithDouble:(jdouble)d;

+ (jdouble)atan2WithDouble:(jdouble)y
                withDouble:(jdouble)x;

+ (jdouble)cbrtWithDouble:(jdouble)d;

+ (jdouble)ceilWithDouble:(jdouble)d;

+ (jdouble)coshWithDouble:(jdouble)d;

+ (jdouble)cosWithDouble:(jdouble)d;

+ (jdouble)expWithDouble:(jdouble)d;

+ (jdouble)expm1WithDouble:(jdouble)d;

+ (jdouble)floorWithDouble:(jdouble)d;

+ (jdouble)hypotWithDouble:(jdouble)x
                withDouble:(jdouble)y;

+ (jdouble)IEEEremainderWithDouble:(jdouble)x
                        withDouble:(jdouble)y;

+ (jdouble)logWithDouble:(jdouble)d;

+ (jdouble)log10WithDouble:(jdouble)d;

+ (jdouble)log1pWithDouble:(jdouble)d;

+ (jdouble)maxWithDouble:(jdouble)d1
              withDouble:(jdouble)d2;

+ (jfloat)maxWithFloat:(jfloat)f1
             withFloat:(jfloat)f2;

+ (jint)maxWithInt:(jint)i1
           withInt:(jint)i2;

+ (jlong)maxWithLong:(jlong)l1
            withLong:(jlong)l2;

+ (jdouble)minWithDouble:(jdouble)d1
              withDouble:(jdouble)d2;

+ (jfloat)minWithFloat:(jfloat)f1
             withFloat:(jfloat)f2;

+ (jint)minWithInt:(jint)i1
           withInt:(jint)i2;

+ (jlong)minWithLong:(jlong)l1
            withLong:(jlong)l2;

+ (jdouble)powWithDouble:(jdouble)x
              withDouble:(jdouble)y;

+ (jdouble)random;

+ (jdouble)rintWithDouble:(jdouble)d;

+ (jlong)roundWithDouble:(jdouble)d;

+ (jint)roundWithFloat:(jfloat)f;

+ (jdouble)signumWithDouble:(jdouble)d;

+ (jfloat)signumWithFloat:(jfloat)f;

+ (jdouble)sinhWithDouble:(jdouble)d;

+ (jdouble)sinWithDouble:(jdouble)d;

+ (jdouble)sqrtWithDouble:(jdouble)d;

+ (jdouble)tanWithDouble:(jdouble)d;

+ (jdouble)tanhWithDouble:(jdouble)d;

+ (jdouble)toDegreesWithDouble:(jdouble)angrad;

+ (jdouble)toRadiansWithDouble:(jdouble)angdeg;

+ (jdouble)ulpWithDouble:(jdouble)d;

+ (jfloat)ulpWithFloat:(jfloat)f;

@end

__attribute__((always_inline)) inline void JavaLangStrictMath_init() {}
FOUNDATION_EXPORT jdouble JavaLangStrictMath_absWithDouble_(jdouble d);
FOUNDATION_EXPORT jfloat JavaLangStrictMath_absWithFloat_(jfloat f);
FOUNDATION_EXPORT jint JavaLangStrictMath_absWithInt_(jint i);
FOUNDATION_EXPORT jlong JavaLangStrictMath_absWithLong_(jlong l);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_acosWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_asinWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_atanWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_atan2WithDouble_withDouble_(jdouble y, jdouble x);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_cbrtWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_ceilWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_coshWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_cosWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_expWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_expm1WithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_floorWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_hypotWithDouble_withDouble_(jdouble x, jdouble y);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_IEEEremainderWithDouble_withDouble_(jdouble x, jdouble y);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_logWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_log10WithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_log1pWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_maxWithDouble_withDouble_(jdouble d1, jdouble d2);
FOUNDATION_EXPORT jfloat JavaLangStrictMath_maxWithFloat_withFloat_(jfloat f1, jfloat f2);
FOUNDATION_EXPORT jint JavaLangStrictMath_maxWithInt_withInt_(jint i1, jint i2);
FOUNDATION_EXPORT jlong JavaLangStrictMath_maxWithLong_withLong_(jlong l1, jlong l2);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_minWithDouble_withDouble_(jdouble d1, jdouble d2);
FOUNDATION_EXPORT jfloat JavaLangStrictMath_minWithFloat_withFloat_(jfloat f1, jfloat f2);
FOUNDATION_EXPORT jint JavaLangStrictMath_minWithInt_withInt_(jint i1, jint i2);
FOUNDATION_EXPORT jlong JavaLangStrictMath_minWithLong_withLong_(jlong l1, jlong l2);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_powWithDouble_withDouble_(jdouble x, jdouble y);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_random();
FOUNDATION_EXPORT jdouble JavaLangStrictMath_rintWithDouble_(jdouble d);
FOUNDATION_EXPORT jlong JavaLangStrictMath_roundWithDouble_(jdouble d);
FOUNDATION_EXPORT jint JavaLangStrictMath_roundWithFloat_(jfloat f);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_signumWithDouble_(jdouble d);
FOUNDATION_EXPORT jfloat JavaLangStrictMath_signumWithFloat_(jfloat f);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_sinhWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_sinWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_sqrtWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_tanWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_tanhWithDouble_(jdouble d);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_toDegreesWithDouble_(jdouble angrad);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_toRadiansWithDouble_(jdouble angdeg);
FOUNDATION_EXPORT jdouble JavaLangStrictMath_ulpWithDouble_(jdouble d);
FOUNDATION_EXPORT jfloat JavaLangStrictMath_ulpWithFloat_(jfloat f);

J2OBJC_STATIC_FIELD_GETTER(JavaLangStrictMath, E, jdouble)

J2OBJC_STATIC_FIELD_GETTER(JavaLangStrictMath, PI, jdouble)

FOUNDATION_EXPORT JavaUtilRandom *JavaLangStrictMath_random__;
J2OBJC_STATIC_FIELD_GETTER(JavaLangStrictMath, random__, JavaUtilRandom *)
J2OBJC_STATIC_FIELD_SETTER(JavaLangStrictMath, random__, JavaUtilRandom *)

#endif // _JavaLangStrictMath_H_
