//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/util/AbstractQueue.java
//

#ifndef _JavaUtilAbstractQueue_H_
#define _JavaUtilAbstractQueue_H_

@protocol JavaUtilCollection;

#import "JreEmulation.h"
#include "java/util/AbstractCollection.h"
#include "java/util/Queue.h"

@interface JavaUtilAbstractQueue : JavaUtilAbstractCollection < JavaUtilQueue > {
}

- (instancetype)init;

- (jboolean)addWithId:(id)o;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (id)remove;

- (id)element;

- (void)clear;


@end

__attribute__((always_inline)) inline void JavaUtilAbstractQueue_init() {}

#endif // _JavaUtilAbstractQueue_H_
