//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/util/Comparator.java
//

#ifndef _JavaUtilComparator_H_
#define _JavaUtilComparator_H_

#import "JreEmulation.h"

@protocol JavaUtilComparator < NSObject, JavaObject >

- (jint)compareWithId:(id)object1
               withId:(id)object2;

@end

__attribute__((always_inline)) inline void JavaUtilComparator_init() {}

#endif // _JavaUtilComparator_H_
