//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/util/Iterator.java
//

#ifndef _JavaUtilIterator_H_
#define _JavaUtilIterator_H_

#import "JreEmulation.h"

@protocol JavaUtilIterator < NSObject, JavaObject >

- (jboolean)hasNext;

- (id)next;

- (void)remove;

@end

__attribute__((always_inline)) inline void JavaUtilIterator_init() {}

#endif // _JavaUtilIterator_H_
