//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/util/Queue.java
//

#ifndef _JavaUtilQueue_H_
#define _JavaUtilQueue_H_

#import "JreEmulation.h"
#include "java/util/Collection.h"

@protocol JavaUtilQueue < JavaUtilCollection, NSObject, JavaObject >
- (jboolean)offerWithId:(id)o;

- (id)poll;

- (id)remove;

- (id)peek;

- (id)element;


@end

__attribute__((always_inline)) inline void JavaUtilQueue_init() {}

#endif // _JavaUtilQueue_H_
