//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/util/Set.java
//

#ifndef _JavaUtilSet_H_
#define _JavaUtilSet_H_

@protocol JavaUtilIterator;

#import "JreEmulation.h"
#include "java/util/Collection.h"

@protocol JavaUtilSet < JavaUtilCollection, NSObject, JavaObject >
- (jboolean)addWithId:(id)object;

- (jboolean)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (void)clear;

- (jboolean)containsWithId:(id)object;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)object;

- (jboolean)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jboolean)retainAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;

- (jint)size;


@end

__attribute__((always_inline)) inline void JavaUtilSet_init() {}

#endif // _JavaUtilSet_H_
