//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/stubbing/InvocationContainer.java
//

#ifndef _OrgMockitoInternalStubbingInvocationContainer_H_
#define _OrgMockitoInternalStubbingInvocationContainer_H_

@protocol JavaUtilList;

#import "JreEmulation.h"

@protocol OrgMockitoInternalStubbingInvocationContainer < NSObject, JavaObject >

- (id<JavaUtilList>)getInvocations;

- (id<JavaUtilList>)getStubbedInvocations;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalStubbingInvocationContainer_init() {}

#endif // _OrgMockitoInternalStubbingInvocationContainer_H_
