//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/org/apache/harmony/luni/util/HistoricalNamesUtil.java
//

#ifndef _OrgApacheHarmonyLuniUtilHistoricalNamesUtil_H_
#define _OrgApacheHarmonyLuniUtilHistoricalNamesUtil_H_

@class JavaUtilHashMap;

#import "JreEmulation.h"

@interface OrgApacheHarmonyLuniUtilHistoricalNamesUtil : NSObject {
}

+ (NSString *)getHistoricalNameWithNSString:(NSString *)name;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgApacheHarmonyLuniUtilHistoricalNamesUtil_initialized;
J2OBJC_STATIC_INIT(OrgApacheHarmonyLuniUtilHistoricalNamesUtil)
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilHistoricalNamesUtil_getHistoricalNameWithNSString_(NSString *name);

FOUNDATION_EXPORT JavaUtilHashMap *OrgApacheHarmonyLuniUtilHistoricalNamesUtil_historicalNames_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyLuniUtilHistoricalNamesUtil, historicalNames_, JavaUtilHashMap *)
J2OBJC_STATIC_FIELD_SETTER(OrgApacheHarmonyLuniUtilHistoricalNamesUtil, historicalNames_, JavaUtilHashMap *)

#endif // _OrgApacheHarmonyLuniUtilHistoricalNamesUtil_H_
