//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/org/apache/harmony/luni/util/Util.java
//

#ifndef _OrgApacheHarmonyLuniUtilUtil_H_
#define _OrgApacheHarmonyLuniUtilUtil_H_

@class IOSByteArray;
@class IOSCharArray;
@class IOSObjectArray;

#import "JreEmulation.h"

@interface OrgApacheHarmonyLuniUtilUtil : NSObject {
}

+ (IOSByteArray *)getBytesWithNSString:(NSString *)name;

+ (IOSByteArray *)getUTF8BytesWithNSString:(NSString *)name;

+ (NSString *)toStringWithByteArray:(IOSByteArray *)bytes;

+ (NSString *)toUTF8StringWithByteArray:(IOSByteArray *)bytes;

+ (NSString *)toStringWithByteArray:(IOSByteArray *)bytes
                            withInt:(jint)offset
                            withInt:(jint)length;

+ (NSString *)toUTF8StringWithByteArray:(IOSByteArray *)bytes
                                withInt:(jint)offset
                                withInt:(jint)length;

+ (jlong)parseDateWithNSString:(NSString *)string;

+ (NSString *)convertFromUTF8WithByteArray:(IOSByteArray *)buf
                                   withInt:(jint)offset
                                   withInt:(jint)utfSize;

+ (NSString *)convertUTF8WithBufWithByteArray:(IOSByteArray *)buf
                                withCharArray:(IOSCharArray *)outArg
                                      withInt:(jint)offset
                                      withInt:(jint)utfSize;

+ (NSString *)decodeWithNSString:(NSString *)s
                     withBoolean:(jboolean)convertPlus;

+ (NSString *)decodeWithNSString:(NSString *)s
                     withBoolean:(jboolean)convertPlus
                    withNSString:(NSString *)encoding;

+ (NSString *)encodeURLWithNSString:(NSString *)urlStr;

+ (NSString *)toASCIILowerCaseWithNSString:(NSString *)s;

+ (NSString *)toASCIIUpperCaseWithNSString:(NSString *)s;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgApacheHarmonyLuniUtilUtil_initialized;
J2OBJC_STATIC_INIT(OrgApacheHarmonyLuniUtilUtil)
FOUNDATION_EXPORT IOSByteArray *OrgApacheHarmonyLuniUtilUtil_getBytesWithNSString_(NSString *name);
FOUNDATION_EXPORT IOSByteArray *OrgApacheHarmonyLuniUtilUtil_getUTF8BytesWithNSString_(NSString *name);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_toStringWithByteArray_(IOSByteArray *bytes);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_toUTF8StringWithByteArray_(IOSByteArray *bytes);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_toStringWithByteArray_withInt_withInt_(IOSByteArray *bytes, jint offset, jint length);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_toUTF8StringWithByteArray_withInt_withInt_(IOSByteArray *bytes, jint offset, jint length);
FOUNDATION_EXPORT jlong OrgApacheHarmonyLuniUtilUtil_parseDateWithNSString_(NSString *string);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_convertFromUTF8WithByteArray_withInt_withInt_(IOSByteArray *buf, jint offset, jint utfSize);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_convertUTF8WithBufWithByteArray_withCharArray_withInt_withInt_(IOSByteArray *buf, IOSCharArray *outArg, jint offset, jint utfSize);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_decodeWithNSString_withBoolean_(NSString *s, jboolean convertPlus);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_decodeWithNSString_withBoolean_withNSString_(NSString *s, jboolean convertPlus, NSString *encoding);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_encodeURLWithNSString_(NSString *urlStr);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_toASCIILowerCaseWithNSString_(NSString *s);
FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_toASCIIUpperCaseWithNSString_(NSString *s);

FOUNDATION_EXPORT IOSObjectArray *OrgApacheHarmonyLuniUtilUtil_WEEKDAYS_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyLuniUtilUtil, WEEKDAYS_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(OrgApacheHarmonyLuniUtilUtil, WEEKDAYS_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *OrgApacheHarmonyLuniUtilUtil_MONTHS_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyLuniUtilUtil, MONTHS_, IOSObjectArray *)
J2OBJC_STATIC_FIELD_SETTER(OrgApacheHarmonyLuniUtilUtil, MONTHS_, IOSObjectArray *)

FOUNDATION_EXPORT NSString *OrgApacheHarmonyLuniUtilUtil_defaultEncoding_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonyLuniUtilUtil, defaultEncoding_, NSString *)

#endif // _OrgApacheHarmonyLuniUtilUtil_H_
