//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/guava/sources/com/google/common/util/concurrent/FutureCallback.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonUtilConcurrentFutureCallback_RESTRICT
#define ComGoogleCommonUtilConcurrentFutureCallback_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonUtilConcurrentFutureCallback_RESTRICT

#if !defined (_ComGoogleCommonUtilConcurrentFutureCallback_) && (ComGoogleCommonUtilConcurrentFutureCallback_INCLUDE_ALL || ComGoogleCommonUtilConcurrentFutureCallback_INCLUDE)
#define _ComGoogleCommonUtilConcurrentFutureCallback_

@class JavaLangThrowable;

@protocol ComGoogleCommonUtilConcurrentFutureCallback < NSObject, JavaObject >

- (void)onSuccessWithId:(id)result;

- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)t;

@end

__attribute__((always_inline)) inline void ComGoogleCommonUtilConcurrentFutureCallback_init() {}
#endif
