//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/progress/HandyReturnValues.java
//

#ifndef _OrgMockitoInternalProgressHandyReturnValues_H_
#define _OrgMockitoInternalProgressHandyReturnValues_H_

@class IOSClass;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#import "JreEmulation.h"

@interface OrgMockitoInternalProgressHandyReturnValues : NSObject {
}

- (jbyte)returnZero;

- (jchar)returnChar;

- (id)returnNull;

- (jboolean)returnFalse;

- (NSString *)returnString;

- (id)returnForWithIOSClass:(IOSClass *)clazz;

- (id<JavaUtilMap>)returnMap;

- (id<JavaUtilList>)returnList;

- (id<JavaUtilSet>)returnSet;

- (id)returnForWithId:(id)instance;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalProgressHandyReturnValues_init() {}

#endif // _OrgMockitoInternalProgressHandyReturnValues_H_
