//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/runner/manipulation/Filterable.java
//

#ifndef _OrgJunitRunnerManipulationFilterable_H_
#define _OrgJunitRunnerManipulationFilterable_H_

@class OrgJunitRunnerManipulationFilter;

#import "JreEmulation.h"

@protocol OrgJunitRunnerManipulationFilterable < NSObject, JavaObject >

- (void)filterWithOrgJunitRunnerManipulationFilter:(OrgJunitRunnerManipulationFilter *)filter;

@end

__attribute__((always_inline)) inline void OrgJunitRunnerManipulationFilterable_init() {}

#endif // _OrgJunitRunnerManipulationFilterable_H_
