//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/guava/sources/com/google/common/collect/Constraint.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectConstraint_RESTRICT
#define ComGoogleCommonCollectConstraint_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectConstraint_RESTRICT

#if !defined (_ComGoogleCommonCollectConstraint_) && (ComGoogleCommonCollectConstraint_INCLUDE_ALL || ComGoogleCommonCollectConstraint_INCLUDE)
#define _ComGoogleCommonCollectConstraint_

@protocol ComGoogleCommonCollectConstraint < NSObject, JavaObject >

- (id)checkElementWithId:(id)element;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectConstraint_init() {}
#endif
