//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/guava/sources/com/google/common/collect/ForwardingImmutableCollection.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectForwardingImmutableCollection_RESTRICT
#define ComGoogleCommonCollectForwardingImmutableCollection_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectForwardingImmutableCollection_RESTRICT

#if !defined (_ComGoogleCommonCollectForwardingImmutableCollection_) && (ComGoogleCommonCollectForwardingImmutableCollection_INCLUDE_ALL || ComGoogleCommonCollectForwardingImmutableCollection_INCLUDE)
#define _ComGoogleCommonCollectForwardingImmutableCollection_

@interface ComGoogleCommonCollectForwardingImmutableCollection : NSObject {
}

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectForwardingImmutableCollection_init() {}
#endif
