//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/guava/sources/com/google/common/collect/MapConstraint.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCollectMapConstraint_RESTRICT
#define ComGoogleCommonCollectMapConstraint_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectMapConstraint_RESTRICT

#if !defined (_ComGoogleCommonCollectMapConstraint_) && (ComGoogleCommonCollectMapConstraint_INCLUDE_ALL || ComGoogleCommonCollectMapConstraint_INCLUDE)
#define _ComGoogleCommonCollectMapConstraint_

@protocol ComGoogleCommonCollectMapConstraint < NSObject, JavaObject >

- (void)checkKeyValueWithId:(id)key
                     withId:(id)value;

- (NSString *)description;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCollectMapConstraint_init() {}
#endif
