//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/After.java
//

#ifndef _OrgJunitAfter_H_
#define _OrgJunitAfter_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitAfter < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitAfter : NSObject < OrgJunitAfter >

@end

__attribute__((always_inline)) inline void OrgJunitAfter_init() {}

#endif // _OrgJunitAfter_H_
