//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/Assume.java
//

#ifndef _OrgJunitAssume_H_
#define _OrgJunitAssume_H_

@class IOSObjectArray;
@class JavaLangThrowable;
@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"

@interface OrgJunitAssume : NSObject {
}

+ (void)assumeTrueWithBoolean:(jboolean)b;

+ (void)assumeNotNullWithNSObjectArray:(IOSObjectArray *)objects;

+ (void)assumeThatWithId:(id)actual
  withOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher;

+ (void)assumeNoExceptionWithJavaLangThrowable:(JavaLangThrowable *)t;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJunitAssume_init() {}

#endif // _OrgJunitAssume_H_
