//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/ClassRule.java
//

#ifndef _OrgJunitClassRule_H_
#define _OrgJunitClassRule_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitClassRule < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitClassRule : NSObject < OrgJunitClassRule >

@end

__attribute__((always_inline)) inline void OrgJunitClassRule_init() {}

#endif // _OrgJunitClassRule_H_
