//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/Rule.java
//

#ifndef _OrgJunitRule_H_
#define _OrgJunitRule_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol OrgJunitRule < JavaLangAnnotationAnnotation >

@end

@interface OrgJunitRule : NSObject < OrgJunitRule >

@end

__attribute__((always_inline)) inline void OrgJunitRule_init() {}

#endif // _OrgJunitRule_H_
