//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/invocation/InvocationOnMock.java
//

#ifndef _OrgMockitoInvocationInvocationOnMock_H_
#define _OrgMockitoInvocationInvocationOnMock_H_

@class IOSObjectArray;
@class JavaLangReflectMethod;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

@protocol OrgMockitoInvocationInvocationOnMock < JavaIoSerializable, NSObject, JavaObject >
- (id)getMock;

- (JavaLangReflectMethod *)getMethod;

- (IOSObjectArray *)getArguments;

- (id)callRealMethod;

@end

__attribute__((always_inline)) inline void OrgMockitoInvocationInvocationOnMock_init() {}

#endif // _OrgMockitoInvocationInvocationOnMock_H_
