//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/invocation/StubInfo.java
//

#ifndef _OrgMockitoInvocationStubInfo_H_
#define _OrgMockitoInvocationStubInfo_H_

@protocol OrgMockitoInvocationLocation;

#import "JreEmulation.h"

@protocol OrgMockitoInvocationStubInfo < NSObject, JavaObject >

- (id<OrgMockitoInvocationLocation>)stubbedAt;

@end

__attribute__((always_inline)) inline void OrgMockitoInvocationStubInfo_init() {}

#endif // _OrgMockitoInvocationStubInfo_H_
