//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/CheckForSigned.java
//

#ifndef _JavaxAnnotationCheckForSigned_H_
#define _JavaxAnnotationCheckForSigned_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationCheckForSigned < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationCheckForSigned : NSObject < JavaxAnnotationCheckForSigned >

@end

__attribute__((always_inline)) inline void JavaxAnnotationCheckForSigned_init() {}

#endif // _JavaxAnnotationCheckForSigned_H_
