//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/Detainted.java
//

#ifndef _JavaxAnnotationDetainted_H_
#define _JavaxAnnotationDetainted_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationDetainted < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationDetainted : NSObject < JavaxAnnotationDetainted >

@end

__attribute__((always_inline)) inline void JavaxAnnotationDetainted_init() {}

#endif // _JavaxAnnotationDetainted_H_
