//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/ParametersAreNonnullByDefault.java
//

#ifndef _JavaxAnnotationParametersAreNonnullByDefault_H_
#define _JavaxAnnotationParametersAreNonnullByDefault_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationParametersAreNonnullByDefault < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationParametersAreNonnullByDefault : NSObject < JavaxAnnotationParametersAreNonnullByDefault >

@end

__attribute__((always_inline)) inline void JavaxAnnotationParametersAreNonnullByDefault_init() {}

#endif // _JavaxAnnotationParametersAreNonnullByDefault_H_
