//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/Signed.java
//

#ifndef _JavaxAnnotationSigned_H_
#define _JavaxAnnotationSigned_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationSigned < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationSigned : NSObject < JavaxAnnotationSigned >

@end

__attribute__((always_inline)) inline void JavaxAnnotationSigned_init() {}

#endif // _JavaxAnnotationSigned_H_
