//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/WillClose.java
//

#ifndef _JavaxAnnotationWillClose_H_
#define _JavaxAnnotationWillClose_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationWillClose < JavaLangAnnotationAnnotation >

@end

@interface JavaxAnnotationWillClose : NSObject < JavaxAnnotationWillClose >

@end

__attribute__((always_inline)) inline void JavaxAnnotationWillClose_init() {}

#endif // _JavaxAnnotationWillClose_H_
