//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/exceptions/util/ScenarioPrinter.java
//

#ifndef _OrgMockitoInternalExceptionsUtilScenarioPrinter_H_
#define _OrgMockitoInternalExceptionsUtilScenarioPrinter_H_

@protocol JavaUtilList;

#import "JreEmulation.h"

@interface OrgMockitoInternalExceptionsUtilScenarioPrinter : NSObject {
}

- (NSString *)printWithJavaUtilList:(id<JavaUtilList>)invocations;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalExceptionsUtilScenarioPrinter_init() {}

#endif // _OrgMockitoInternalExceptionsUtilScenarioPrinter_H_
