//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/junit/textui/TestRunner.java
//

#ifndef _JunitTextuiTestRunner_H_
#define _JunitTextuiTestRunner_H_

@class IOSClass;
@class IOSObjectArray;
@class JavaIoPrintStream;
@class JavaLangThrowable;
@class JunitFrameworkTestResult;
@class JunitTextuiResultPrinter;
@protocol JunitFrameworkTest;

#import "JreEmulation.h"
#include "junit/runner/BaseTestRunner.h"

#define JunitTextuiTestRunner_EXCEPTION_EXIT 2
#define JunitTextuiTestRunner_FAILURE_EXIT 1
#define JunitTextuiTestRunner_SUCCESS_EXIT 0

@interface JunitTextuiTestRunner : JunitRunnerBaseTestRunner {
 @public
  JunitTextuiResultPrinter *fPrinter_;
}

- (instancetype)init;

- (instancetype)initWithJavaIoPrintStream:(JavaIoPrintStream *)writer;

- (instancetype)initWithJunitTextuiResultPrinter:(JunitTextuiResultPrinter *)printer;

+ (void)runWithIOSClass:(IOSClass *)testClass;

+ (JunitFrameworkTestResult *)runWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;

+ (void)runAndWaitWithJunitFrameworkTest:(id<JunitFrameworkTest>)suite;

- (void)testFailedWithInt:(jint)status
   withJunitFrameworkTest:(id<JunitFrameworkTest>)test
    withJavaLangThrowable:(JavaLangThrowable *)t;

- (void)testStartedWithNSString:(NSString *)testName;

- (void)testEndedWithNSString:(NSString *)testName;

- (JunitFrameworkTestResult *)createTestResult;

- (JunitFrameworkTestResult *)doRunWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;

- (JunitFrameworkTestResult *)doRunWithJunitFrameworkTest:(id<JunitFrameworkTest>)suite
                                              withBoolean:(jboolean)wait;

- (void)pauseWithBoolean:(jboolean)wait;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

- (JunitFrameworkTestResult *)startWithNSStringArray:(IOSObjectArray *)args;

- (JunitFrameworkTestResult *)runSingleMethodWithNSString:(NSString *)testCase
                                             withNSString:(NSString *)method
                                              withBoolean:(jboolean)wait;

- (void)runFailedWithNSString:(NSString *)message;

- (void)setPrinterWithJunitTextuiResultPrinter:(JunitTextuiResultPrinter *)printer;

- (void)dealloc;

- (void)copyAllFieldsTo:(JunitTextuiTestRunner *)other;

@end

__attribute__((always_inline)) inline void JunitTextuiTestRunner_init() {}

J2OBJC_FIELD_SETTER(JunitTextuiTestRunner, fPrinter_, JunitTextuiResultPrinter *)

J2OBJC_STATIC_FIELD_GETTER(JunitTextuiTestRunner, SUCCESS_EXIT, jint)

J2OBJC_STATIC_FIELD_GETTER(JunitTextuiTestRunner, FAILURE_EXIT, jint)

J2OBJC_STATIC_FIELD_GETTER(JunitTextuiTestRunner, EXCEPTION_EXIT, jint)

#endif // _JunitTextuiTestRunner_H_
