//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/exceptions/verification/TooLittleActualInvocations.java
//

#ifndef _OrgMockitoExceptionsVerificationTooLittleActualInvocations_H_
#define _OrgMockitoExceptionsVerificationTooLittleActualInvocations_H_

#import "JreEmulation.h"
#include "org/mockito/exceptions/base/MockitoAssertionError.h"

#define OrgMockitoExceptionsVerificationTooLittleActualInvocations_serialVersionUID 1LL

@interface OrgMockitoExceptionsVerificationTooLittleActualInvocations : OrgMockitoExceptionsBaseMockitoAssertionError {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsVerificationTooLittleActualInvocations_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsVerificationTooLittleActualInvocations, serialVersionUID, jlong)

#endif // _OrgMockitoExceptionsVerificationTooLittleActualInvocations_H_
