//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/util/collections/IdentitySet.java
//

#ifndef _OrgMockitoInternalUtilCollectionsIdentitySet_H_
#define _OrgMockitoInternalUtilCollectionsIdentitySet_H_

@class JavaUtilLinkedList;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilCollectionsIdentitySet : NSObject {
 @public
  JavaUtilLinkedList *list_;
}

- (jboolean)containsWithId:(id)o;

- (void)addWithId:(id)o;

- (instancetype)init;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalUtilCollectionsIdentitySet *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilCollectionsIdentitySet_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalUtilCollectionsIdentitySet, list_, JavaUtilLinkedList *)

#endif // _OrgMockitoInternalUtilCollectionsIdentitySet_H_
