//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/util/collections/ListUtil.java
//

#ifndef _OrgMockitoInternalUtilCollectionsListUtil_H_
#define _OrgMockitoInternalUtilCollectionsListUtil_H_

@class JavaUtilLinkedList;
@protocol JavaUtilCollection;
@protocol OrgMockitoInternalUtilCollectionsListUtil_Filter;

#import "JreEmulation.h"

@interface OrgMockitoInternalUtilCollectionsListUtil : NSObject {
}

+ (JavaUtilLinkedList *)filterWithJavaUtilCollection:(id<JavaUtilCollection>)collection
withOrgMockitoInternalUtilCollectionsListUtil_Filter:(id<OrgMockitoInternalUtilCollectionsListUtil_Filter>)filter;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilCollectionsListUtil_init() {}

@protocol OrgMockitoInternalUtilCollectionsListUtil_Filter < NSObject, JavaObject >

- (jboolean)isOutWithId:(id)object;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalUtilCollectionsListUtil_Filter_init() {}

#endif // _OrgMockitoInternalUtilCollectionsListUtil_H_
