//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/matchers/AnyVararg.java
//

#ifndef _OrgMockitoInternalMatchersAnyVararg_H_
#define _OrgMockitoInternalMatchersAnyVararg_H_

@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "org/mockito/ArgumentMatcher.h"
#include "org/mockito/internal/matchers/VarargMatcher.h"

#define OrgMockitoInternalMatchersAnyVararg_serialVersionUID 1700721373094731555LL

@interface OrgMockitoInternalMatchersAnyVararg : OrgMockitoArgumentMatcher < OrgMockitoInternalMatchersVarargMatcher, JavaIoSerializable > {
}

- (jboolean)matchesWithId:(id)arg;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgMockitoInternalMatchersAnyVararg_initialized;
J2OBJC_STATIC_INIT(OrgMockitoInternalMatchersAnyVararg)

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalMatchersAnyVararg, serialVersionUID, jlong)

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgMockitoInternalMatchersAnyVararg_ANY_VARARG_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalMatchersAnyVararg, ANY_VARARG_, id<OrgHamcrestMatcher>)

#endif // _OrgMockitoInternalMatchersAnyVararg_H_
