//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/matchers/ContainsExtraTypeInformation.java
//

#ifndef _OrgMockitoInternalMatchersContainsExtraTypeInformation_H_
#define _OrgMockitoInternalMatchersContainsExtraTypeInformation_H_

@protocol OrgHamcrestSelfDescribing;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

@protocol OrgMockitoInternalMatchersContainsExtraTypeInformation < JavaIoSerializable, NSObject, JavaObject >
- (id<OrgHamcrestSelfDescribing>)withExtraTypeInfo;

- (jboolean)typeMatchesWithId:(id)object;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalMatchersContainsExtraTypeInformation_init() {}

#endif // _OrgMockitoInternalMatchersContainsExtraTypeInformation_H_
