//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/matchers/Contains.java
//

#ifndef _OrgMockitoInternalMatchersContains_H_
#define _OrgMockitoInternalMatchersContains_H_

@protocol OrgHamcrestDescription;

#import "JreEmulation.h"
#include "java/io/Serializable.h"
#include "org/mockito/ArgumentMatcher.h"

#define OrgMockitoInternalMatchersContains_serialVersionUID -1909837398271763801LL

@interface OrgMockitoInternalMatchersContains : OrgMockitoArgumentMatcher < JavaIoSerializable > {
 @public
  NSString *substring_;
}

- (instancetype)initWithNSString:(NSString *)substring;

- (jboolean)matchesWithId:(id)actual;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgMockitoInternalMatchersContains *)other;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalMatchersContains_init() {}

J2OBJC_FIELD_SETTER(OrgMockitoInternalMatchersContains, substring_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalMatchersContains, serialVersionUID, jlong)

#endif // _OrgMockitoInternalMatchersContains_H_
