//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/matchers/Equality.java
//

#ifndef _OrgMockitoInternalMatchersEquality_H_
#define _OrgMockitoInternalMatchersEquality_H_

#import "JreEmulation.h"

@interface OrgMockitoInternalMatchersEquality : NSObject {
}

+ (jboolean)areEqualWithId:(id)o1
                    withId:(id)o2;

+ (jboolean)areArraysEqualWithId:(id)o1
                          withId:(id)o2;

+ (jboolean)areArrayLengthsEqualWithId:(id)o1
                                withId:(id)o2;

+ (jboolean)areArrayElementsEqualWithId:(id)o1
                                 withId:(id)o2;

+ (jboolean)isArrayWithId:(id)o;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalMatchersEquality_init() {}

#endif // _OrgMockitoInternalMatchersEquality_H_
