//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/matchers/VarargMatcher.java
//

#ifndef _OrgMockitoInternalMatchersVarargMatcher_H_
#define _OrgMockitoInternalMatchersVarargMatcher_H_

#import "JreEmulation.h"
#include "java/io/Serializable.h"

@protocol OrgMockitoInternalMatchersVarargMatcher < JavaIoSerializable, NSObject, JavaObject >
@end

__attribute__((always_inline)) inline void OrgMockitoInternalMatchersVarargMatcher_init() {}

#endif // _OrgMockitoInternalMatchersVarargMatcher_H_
