//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/guava/sources/com/google/common/cache/LongAddable.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCacheLongAddable_RESTRICT
#define ComGoogleCommonCacheLongAddable_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCacheLongAddable_RESTRICT

#if !defined (_ComGoogleCommonCacheLongAddable_) && (ComGoogleCommonCacheLongAddable_INCLUDE_ALL || ComGoogleCommonCacheLongAddable_INCLUDE)
#define _ComGoogleCommonCacheLongAddable_

@protocol ComGoogleCommonCacheLongAddable < NSObject, JavaObject >

- (void)increment;

- (void)addWithLong:(jlong)x;

- (jlong)sum;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCacheLongAddable_init() {}
#endif
