//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/guava/sources/com/google/common/cache/RemovalListener.java
//

#import "JreEmulation.h"

#if !ComGoogleCommonCacheRemovalListener_RESTRICT
#define ComGoogleCommonCacheRemovalListener_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCacheRemovalListener_RESTRICT

#if !defined (_ComGoogleCommonCacheRemovalListener_) && (ComGoogleCommonCacheRemovalListener_INCLUDE_ALL || ComGoogleCommonCacheRemovalListener_INCLUDE)
#define _ComGoogleCommonCacheRemovalListener_

@class ComGoogleCommonCacheRemovalNotification;

@protocol ComGoogleCommonCacheRemovalListener < NSObject, JavaObject >

- (void)onRemovalWithComGoogleCommonCacheRemovalNotification:(ComGoogleCommonCacheRemovalNotification *)notification;

@end

__attribute__((always_inline)) inline void ComGoogleCommonCacheRemovalListener_init() {}
#endif
