//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/inject/javax_inject/build_result/java/javax/inject/Inject.java
//

#ifndef _JavaxInjectInject_H_
#define _JavaxInjectInject_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxInjectInject < JavaLangAnnotationAnnotation >

@end

@interface JavaxInjectInject : NSObject < JavaxInjectInject >

@end

__attribute__((always_inline)) inline void JavaxInjectInject_init() {}

#endif // _JavaxInjectInject_H_
