//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/inject/javax_inject/build_result/java/javax/inject/Qualifier.java
//

#ifndef _JavaxInjectQualifier_H_
#define _JavaxInjectQualifier_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxInjectQualifier < JavaLangAnnotationAnnotation >

@end

@interface JavaxInjectQualifier : NSObject < JavaxInjectQualifier >

@end

__attribute__((always_inline)) inline void JavaxInjectQualifier_init() {}

#endif // _JavaxInjectQualifier_H_
