//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/mockito/internal/configuration/ClassPathLoader.java
//

#ifndef _OrgMockitoInternalConfigurationClassPathLoader_H_
#define _OrgMockitoInternalConfigurationClassPathLoader_H_

@class IOSClass;
@class JavaIoInputStream;
@class JavaIoReader;
@protocol JavaUtilList;
@protocol OrgMockitoConfigurationIMockitoConfiguration;
@protocol OrgMockitoPluginsMockMaker;
@protocol OrgMockitoPluginsStackTraceCleanerProvider;

#import "JreEmulation.h"

@interface OrgMockitoInternalConfigurationClassPathLoader : NSObject {
}

- (id<OrgMockitoConfigurationIMockitoConfiguration>)loadConfiguration;

+ (id<OrgMockitoPluginsMockMaker>)getMockMaker;

+ (id<OrgMockitoPluginsStackTraceCleanerProvider>)getStackTraceCleanerProvider;

+ (id<OrgMockitoPluginsMockMaker>)findPlatformMockMaker;

+ (id)findPluginImplementationWithIOSClass:(IOSClass *)pluginType
                                    withId:(id)defaultPlugin;

+ (id<JavaUtilList>)loadImplementationsWithIOSClass:(IOSClass *)service;

+ (id<JavaUtilList>)readerToLinesWithJavaIoReader:(JavaIoReader *)reader;

+ (NSString *)stripCommentAndWhitespaceWithNSString:(NSString *)line;

+ (void)closeQuietlyWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgMockitoInternalConfigurationClassPathLoader_initialized;
J2OBJC_STATIC_INIT(OrgMockitoInternalConfigurationClassPathLoader)

FOUNDATION_EXPORT id<OrgMockitoPluginsMockMaker> OrgMockitoInternalConfigurationClassPathLoader_mockMaker_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalConfigurationClassPathLoader, mockMaker_, id<OrgMockitoPluginsMockMaker>)

FOUNDATION_EXPORT id<OrgMockitoPluginsStackTraceCleanerProvider> OrgMockitoInternalConfigurationClassPathLoader_stackTraceCleanerProvider_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalConfigurationClassPathLoader, stackTraceCleanerProvider_, id<OrgMockitoPluginsStackTraceCleanerProvider>)

FOUNDATION_EXPORT NSString *OrgMockitoInternalConfigurationClassPathLoader_MOCKITO_CONFIGURATION_CLASS_NAME_;
J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalConfigurationClassPathLoader, MOCKITO_CONFIGURATION_CLASS_NAME_, NSString *)

#endif // _OrgMockitoInternalConfigurationClassPathLoader_H_
