//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/configuration/DefaultInjectionEngine.java
//

#ifndef _OrgMockitoInternalConfigurationDefaultInjectionEngine_H_
#define _OrgMockitoInternalConfigurationDefaultInjectionEngine_H_

@protocol JavaUtilSet;

#import "JreEmulation.h"

@interface OrgMockitoInternalConfigurationDefaultInjectionEngine : NSObject {
}

- (void)injectMocksOnFieldsWithJavaUtilSet:(id<JavaUtilSet>)needingInjection
                           withJavaUtilSet:(id<JavaUtilSet>)mocks
                                    withId:(id)testClassInstance;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalConfigurationDefaultInjectionEngine_init() {}

#endif // _OrgMockitoInternalConfigurationDefaultInjectionEngine_H_
