//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/runner/Description.java
//

#ifndef _OrgJunitRunnerDescription_H_
#define _OrgJunitRunnerDescription_H_

@class IOSClass;
@class IOSObjectArray;
@class JavaUtilArrayList;
@class JavaUtilRegexMatcher;
@protocol JavaLangAnnotationAnnotation;
@protocol JavaUtilCollection;

#import "JreEmulation.h"
#include "java/io/Serializable.h"

#define OrgJunitRunnerDescription_serialVersionUID 1LL

@interface OrgJunitRunnerDescription : NSObject < JavaIoSerializable > {
 @public
  JavaUtilArrayList *fChildren_;
  NSString *fDisplayName_;
  IOSObjectArray *fAnnotations_;
}

+ (OrgJunitRunnerDescription *)createSuiteDescriptionWithNSString:(NSString *)name
                            withJavaLangAnnotationAnnotationArray:(IOSObjectArray *)annotations;

+ (OrgJunitRunnerDescription *)createTestDescriptionWithIOSClass:(IOSClass *)clazz
                                                    withNSString:(NSString *)name
                           withJavaLangAnnotationAnnotationArray:(IOSObjectArray *)annotations;

+ (OrgJunitRunnerDescription *)createTestDescriptionWithIOSClass:(IOSClass *)clazz
                                                    withNSString:(NSString *)name;

+ (OrgJunitRunnerDescription *)createSuiteDescriptionWithIOSClass:(IOSClass *)testClass;

- (instancetype)initWithNSString:(NSString *)displayName
withJavaLangAnnotationAnnotationArray:(IOSObjectArray *)annotations;

- (NSString *)getDisplayName;

- (void)addChildWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (JavaUtilArrayList *)getChildren;

- (jboolean)isSuite;

- (jboolean)isTest;

- (jint)testCount;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

- (NSString *)description;

- (jboolean)isEmpty;

- (OrgJunitRunnerDescription *)childlessCopy;

- (id)getAnnotationWithIOSClass:(IOSClass *)annotationType;

- (id<JavaUtilCollection>)getAnnotations;

- (IOSClass *)getTestClass;

- (NSString *)getClassName;

- (NSString *)getMethodName;

- (NSString *)parseMethod;

- (JavaUtilRegexMatcher *)methodStringMatcher;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgJunitRunnerDescription *)other;

@end

FOUNDATION_EXPORT BOOL OrgJunitRunnerDescription_initialized;
J2OBJC_STATIC_INIT(OrgJunitRunnerDescription)

J2OBJC_FIELD_SETTER(OrgJunitRunnerDescription, fChildren_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(OrgJunitRunnerDescription, fDisplayName_, NSString *)
J2OBJC_FIELD_SETTER(OrgJunitRunnerDescription, fAnnotations_, IOSObjectArray *)

J2OBJC_STATIC_FIELD_GETTER(OrgJunitRunnerDescription, serialVersionUID, jlong)

FOUNDATION_EXPORT OrgJunitRunnerDescription *OrgJunitRunnerDescription_EMPTY_;
J2OBJC_STATIC_FIELD_GETTER(OrgJunitRunnerDescription, EMPTY_, OrgJunitRunnerDescription *)

FOUNDATION_EXPORT OrgJunitRunnerDescription *OrgJunitRunnerDescription_TEST_MECHANISM_;
J2OBJC_STATIC_FIELD_GETTER(OrgJunitRunnerDescription, TEST_MECHANISM_, OrgJunitRunnerDescription *)

#endif // _OrgJunitRunnerDescription_H_
