//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/runner/JUnitCore.java
//

#ifndef _OrgJunitRunnerJUnitCore_H_
#define _OrgJunitRunnerJUnitCore_H_

@class IOSObjectArray;
@class OrgJunitRunnerComputer;
@class OrgJunitRunnerNotificationRunListener;
@class OrgJunitRunnerNotificationRunNotifier;
@class OrgJunitRunnerRequest;
@class OrgJunitRunnerResult;
@class OrgJunitRunnerRunner;
@protocol JunitFrameworkTest;
@protocol OrgJunitInternalJUnitSystem;

#import "JreEmulation.h"

@interface OrgJunitRunnerJUnitCore : NSObject {
 @public
  OrgJunitRunnerNotificationRunNotifier *fNotifier_;
}

- (instancetype)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

+ (void)runMainAndExitWithOrgJunitInternalJUnitSystem:(id<OrgJunitInternalJUnitSystem>)system
                                    withNSStringArray:(IOSObjectArray *)args;

+ (OrgJunitRunnerResult *)runClassesWithOrgJunitRunnerComputer:(OrgJunitRunnerComputer *)computer
                                             withIOSClassArray:(IOSObjectArray *)classes;

+ (OrgJunitRunnerResult *)runClassesWithIOSClassArray:(IOSObjectArray *)classes;

- (OrgJunitRunnerResult *)runMainWithOrgJunitInternalJUnitSystem:(id<OrgJunitInternalJUnitSystem>)system
                                               withNSStringArray:(IOSObjectArray *)args;

- (NSString *)getVersion;

- (OrgJunitRunnerResult *)runWithIOSClassArray:(IOSObjectArray *)classes;

- (OrgJunitRunnerResult *)runWithOrgJunitRunnerComputer:(OrgJunitRunnerComputer *)computer
                                      withIOSClassArray:(IOSObjectArray *)classes;

- (OrgJunitRunnerResult *)runWithOrgJunitRunnerRequest:(OrgJunitRunnerRequest *)request;

- (OrgJunitRunnerResult *)runWithJunitFrameworkTest:(id<JunitFrameworkTest>)test;

- (OrgJunitRunnerResult *)runWithOrgJunitRunnerRunner:(OrgJunitRunnerRunner *)runner;

- (void)addListenerWithOrgJunitRunnerNotificationRunListener:(OrgJunitRunnerNotificationRunListener *)listener;

- (void)removeListenerWithOrgJunitRunnerNotificationRunListener:(OrgJunitRunnerNotificationRunListener *)listener;

+ (OrgJunitRunnerComputer *)defaultComputer;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgJunitRunnerJUnitCore *)other;

@end

__attribute__((always_inline)) inline void OrgJunitRunnerJUnitCore_init() {}

J2OBJC_FIELD_SETTER(OrgJunitRunnerJUnitCore, fNotifier_, OrgJunitRunnerNotificationRunNotifier *)

#endif // _OrgJunitRunnerJUnitCore_H_
