//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/runner/Runner.java
//

#ifndef _OrgJunitRunnerRunner_H_
#define _OrgJunitRunnerRunner_H_

@class OrgJunitRunnerDescription;
@class OrgJunitRunnerNotificationRunNotifier;

#import "JreEmulation.h"
#include "org/junit/runner/Describable.h"

@interface OrgJunitRunnerRunner : NSObject < OrgJunitRunnerDescribable > {
}

- (OrgJunitRunnerDescription *)getDescription;

- (void)runWithOrgJunitRunnerNotificationRunNotifier:(OrgJunitRunnerNotificationRunNotifier *)notifier;

- (jint)testCount;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJunitRunnerRunner_init() {}

#endif // _OrgJunitRunnerRunner_H_
