//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/invocation/ArgumentsProcessor.java
//

#ifndef _OrgMockitoInternalInvocationArgumentsProcessor_H_
#define _OrgMockitoInternalInvocationArgumentsProcessor_H_

@class IOSObjectArray;
@protocol JavaUtilList;

#import "JreEmulation.h"

@interface OrgMockitoInternalInvocationArgumentsProcessor : NSObject {
}

+ (IOSObjectArray *)expandVarArgsWithBoolean:(jboolean)isVarArgs
                           withNSObjectArray:(IOSObjectArray *)args;

+ (id<JavaUtilList>)argumentsToMatchersWithNSObjectArray:(IOSObjectArray *)arguments;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalInvocationArgumentsProcessor_init() {}

#endif // _OrgMockitoInternalInvocationArgumentsProcessor_H_
