//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/invocation/CapturesArgumensFromInvocation.java
//

#ifndef _OrgMockitoInternalInvocationCapturesArgumensFromInvocation_H_
#define _OrgMockitoInternalInvocationCapturesArgumensFromInvocation_H_

@protocol OrgMockitoInvocationInvocation;

#import "JreEmulation.h"

@protocol OrgMockitoInternalInvocationCapturesArgumensFromInvocation < NSObject, JavaObject >

- (void)captureArgumentsFromWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)i;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalInvocationCapturesArgumensFromInvocation_init() {}

#endif // _OrgMockitoInternalInvocationCapturesArgumensFromInvocation_H_
