//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/rules/RunRules.java
//

#ifndef _OrgJunitRulesRunRules_H_
#define _OrgJunitRulesRunRules_H_

@class OrgJunitRunnerDescription;
@protocol JavaLangIterable;

#import "JreEmulation.h"
#include "org/junit/runners/model/Statement.h"

@interface OrgJunitRulesRunRules : OrgJunitRunnersModelStatement {
 @public
  OrgJunitRunnersModelStatement *statement_;
}

- (instancetype)initWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)base
                                 withJavaLangIterable:(id<JavaLangIterable>)rules
                        withOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (void)evaluate;

+ (OrgJunitRunnersModelStatement *)applyAllWithOrgJunitRunnersModelStatement:(OrgJunitRunnersModelStatement *)result
                                                        withJavaLangIterable:(id<JavaLangIterable>)rules
                                               withOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgJunitRulesRunRules *)other;

@end

__attribute__((always_inline)) inline void OrgJunitRulesRunRules_init() {}

J2OBJC_FIELD_SETTER(OrgJunitRulesRunRules, statement_, OrgJunitRunnersModelStatement *)

#endif // _OrgJunitRulesRunRules_H_
