//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/reporting/Pluralizer.java
//

#ifndef _OrgMockitoInternalReportingPluralizer_H_
#define _OrgMockitoInternalReportingPluralizer_H_

#import "JreEmulation.h"

@interface OrgMockitoInternalReportingPluralizer : NSObject {
}

+ (NSString *)pluralizeWithInt:(jint)number;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalReportingPluralizer_init() {}

#endif // _OrgMockitoInternalReportingPluralizer_H_
