//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/junit/runners/model/Statement.java
//

#ifndef _OrgJunitRunnersModelStatement_H_
#define _OrgJunitRunnersModelStatement_H_

#import "JreEmulation.h"

@interface OrgJunitRunnersModelStatement : NSObject {
}

- (void)evaluate;

- (instancetype)init;

@end

__attribute__((always_inline)) inline void OrgJunitRunnersModelStatement_init() {}

#endif // _OrgJunitRunnersModelStatement_H_
