//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/hamcrest/core/AllOf.java
//

#ifndef _OrgHamcrestCoreAllOf_H_
#define _OrgHamcrestCoreAllOf_H_

@class IOSObjectArray;
@protocol JavaLangIterable;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"
#include "org/hamcrest/BaseMatcher.h"

@interface OrgHamcrestCoreAllOf : OrgHamcrestBaseMatcher {
 @public
  id<JavaLangIterable> matchers_;
}

- (instancetype)initWithJavaLangIterable:(id<JavaLangIterable>)matchers;

- (jboolean)matchesWithId:(id)o;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

+ (id<OrgHamcrestMatcher>)allOfWithOrgHamcrestMatcherArray:(IOSObjectArray *)matchers;

+ (id<OrgHamcrestMatcher>)allOfWithJavaLangIterable:(id<JavaLangIterable>)matchers;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgHamcrestCoreAllOf *)other;

@end

__attribute__((always_inline)) inline void OrgHamcrestCoreAllOf_init() {}

J2OBJC_FIELD_SETTER(OrgHamcrestCoreAllOf, matchers_, id<JavaLangIterable>)

#endif // _OrgHamcrestCoreAllOf_H_
