//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/hamcrest/core/AnyOf.java
//

#ifndef _OrgHamcrestCoreAnyOf_H_
#define _OrgHamcrestCoreAnyOf_H_

@class IOSObjectArray;
@protocol JavaLangIterable;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"
#include "org/hamcrest/BaseMatcher.h"

@interface OrgHamcrestCoreAnyOf : OrgHamcrestBaseMatcher {
 @public
  id<JavaLangIterable> matchers_;
}

- (instancetype)initWithJavaLangIterable:(id<JavaLangIterable>)matchers;

- (jboolean)matchesWithId:(id)o;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

+ (id<OrgHamcrestMatcher>)anyOfWithOrgHamcrestMatcherArray:(IOSObjectArray *)matchers;

+ (id<OrgHamcrestMatcher>)anyOfWithJavaLangIterable:(id<JavaLangIterable>)matchers;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgHamcrestCoreAnyOf *)other;

@end

__attribute__((always_inline)) inline void OrgHamcrestCoreAnyOf_init() {}

J2OBJC_FIELD_SETTER(OrgHamcrestCoreAnyOf, matchers_, id<JavaLangIterable>)

#endif // _OrgHamcrestCoreAnyOf_H_
