//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/junit/build_result/java/org/hamcrest/core/IsInstanceOf.java
//

#ifndef _OrgHamcrestCoreIsInstanceOf_H_
#define _OrgHamcrestCoreIsInstanceOf_H_

@class IOSClass;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

#import "JreEmulation.h"
#include "org/hamcrest/BaseMatcher.h"

@interface OrgHamcrestCoreIsInstanceOf : OrgHamcrestBaseMatcher {
 @public
  IOSClass *theClass_;
}

- (instancetype)initWithIOSClass:(IOSClass *)theClass;

- (jboolean)matchesWithId:(id)item;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

+ (id<OrgHamcrestMatcher>)instanceOfWithIOSClass:(IOSClass *)type;

- (void)dealloc;

- (void)copyAllFieldsTo:(OrgHamcrestCoreIsInstanceOf *)other;

@end

__attribute__((always_inline)) inline void OrgHamcrestCoreIsInstanceOf_init() {}

J2OBJC_FIELD_SETTER(OrgHamcrestCoreIsInstanceOf, theClass_, IOSClass *)

#endif // _OrgHamcrestCoreIsInstanceOf_H_
