//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/internal/invocation/realmethod/RealMethod.java
//

#ifndef _OrgMockitoInternalInvocationRealmethodRealMethod_H_
#define _OrgMockitoInternalInvocationRealmethodRealMethod_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@protocol OrgMockitoInternalInvocationRealmethodRealMethod < NSObject, JavaObject >

- (id)invokeWithId:(id)target
 withNSObjectArray:(IOSObjectArray *)arguments;

@end

__attribute__((always_inline)) inline void OrgMockitoInternalInvocationRealmethodRealMethod_init() {}

#endif // _OrgMockitoInternalInvocationRealmethodRealMethod_H_
