//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/exceptions/misusing/FriendlyReminderException.java
//

#ifndef _OrgMockitoExceptionsMisusingFriendlyReminderException_H_
#define _OrgMockitoExceptionsMisusingFriendlyReminderException_H_

#import "JreEmulation.h"
#include "org/mockito/exceptions/base/MockitoException.h"

#define OrgMockitoExceptionsMisusingFriendlyReminderException_serialVersionUID 1LL

@interface OrgMockitoExceptionsMisusingFriendlyReminderException : OrgMockitoExceptionsBaseMockitoException {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsMisusingFriendlyReminderException_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsMisusingFriendlyReminderException, serialVersionUID, jlong)

#endif // _OrgMockitoExceptionsMisusingFriendlyReminderException_H_
