//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/exceptions/misusing/MissingMethodInvocationException.java
//

#ifndef _OrgMockitoExceptionsMisusingMissingMethodInvocationException_H_
#define _OrgMockitoExceptionsMisusingMissingMethodInvocationException_H_

#import "JreEmulation.h"
#include "org/mockito/exceptions/base/MockitoException.h"

#define OrgMockitoExceptionsMisusingMissingMethodInvocationException_serialVersionUID 1LL

@interface OrgMockitoExceptionsMisusingMissingMethodInvocationException : OrgMockitoExceptionsBaseMockitoException {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsMisusingMissingMethodInvocationException_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsMisusingMissingMethodInvocationException, serialVersionUID, jlong)

#endif // _OrgMockitoExceptionsMisusingMissingMethodInvocationException_H_
