//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/testing/mockito/build_result/java/org/mockito/exceptions/misusing/WrongTypeOfReturnValue.java
//

#ifndef _OrgMockitoExceptionsMisusingWrongTypeOfReturnValue_H_
#define _OrgMockitoExceptionsMisusingWrongTypeOfReturnValue_H_

#import "JreEmulation.h"
#include "org/mockito/exceptions/base/MockitoException.h"

#define OrgMockitoExceptionsMisusingWrongTypeOfReturnValue_serialVersionUID 1LL

@interface OrgMockitoExceptionsMisusingWrongTypeOfReturnValue : OrgMockitoExceptionsBaseMockitoException {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

__attribute__((always_inline)) inline void OrgMockitoExceptionsMisusingWrongTypeOfReturnValue_init() {}

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsMisusingWrongTypeOfReturnValue, serialVersionUID, jlong)

#endif // _OrgMockitoExceptionsMisusingWrongTypeOfReturnValue_H_
