//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/Zetzsche/Development/j2objc-0.9.4/jsr305/build_result/java/javax/annotation/concurrent/Immutable.java
//

#ifndef _JavaxAnnotationConcurrentImmutable_H_
#define _JavaxAnnotationConcurrentImmutable_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol JavaxAnnotationConcurrentImmutable < JavaLangAnnotationAnnotation >

@end

#endif // _JavaxAnnotationConcurrentImmutable_H_
